---
version: '3'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-1:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker-1
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker-1:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
   
  #schema-registry:
  #  image: confluentinc/cp-schema-registry:7.3.0
  #  container_name: schema-register-1
  #  depends_on:
  #    - zookeeper-1
  #    - broker-1
  #  environment:
  #    SCHEMA_REGISTRY_HOST_NAME: localhost 
  #    SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-1:2181
  #    SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:18081    
  #    SCHEMA_REGISTRY_DEBUG: "true"
  #  ports:
  #  -   "18081:18081"